import { supabaseAdminClient } from '../src/config/supabase';

const companies = [
  {
    name: 'OpenAI',
    slug: 'openai',
    description: 'AI research and deployment company creating safe AGI. Known for GPT-4, ChatGPT, DALL-E, and Whisper.',
    category: 'Foundation Models',
    funding_total: 11300000000,
    employee_count: 770,
    founded_year: 2015,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/openai.com',
    website: 'https://openai.com',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 86000000000,
    growth_score: 98,
    data_confidence_score: 95,
  },
  {
    name: 'Anthropic',
    slug: 'anthropic',
    description: 'AI safety and research company building reliable, interpretable, and steerable AI systems. Creators of Claude.',
    category: 'Foundation Models',
    funding_total: 7600000000,
    employee_count: 500,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/anthropic.com',
    website: 'https://anthropic.com',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 18400000000,
    growth_score: 95,
    data_confidence_score: 90,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description: 'AI-powered answer engine providing accurate, sourced answers to complex questions.',
    category: 'AI Applications',
    funding_total: 165000000,
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/perplexity.ai',
    website: 'https://perplexity.ai',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 92,
    data_confidence_score: 85,
  },
  {
    name: 'Mistral AI',
    slug: 'mistral-ai',
    description: 'European AI company developing open-weight and optimized language models.',
    category: 'Foundation Models',
    funding_total: 1130000000,
    employee_count: 80,
    founded_year: 2023,
    hq_city: 'Paris',
    hq_country: 'France',
    logo_url: 'https://logo.clearbit.com/mistral.ai',
    website: 'https://mistral.ai',
    stage: 'Series A',
    is_unicorn: true,
    valuation: 6000000000,
    growth_score: 88,
    data_confidence_score: 90,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    description: 'AI-first code editor built for pair programming with AI. Fork of VS Code with integrated AI capabilities.',
    category: 'AI Applications',
    funding_total: 100000000,
    employee_count: 40,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/cursor.com',
    website: 'https://cursor.sh',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 400000000,
    growth_score: 85,
    data_confidence_score: 80,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'Independent research lab exploring new mediums of thought and expanding imaginative powers through AI image generation.',
    category: 'Generative Media',
    funding_total: 0,
    employee_count: 11,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/midjourney.com',
    website: 'https://midjourney.com',
    stage: 'Seed',
    is_unicorn: false,
    valuation: 0,
    growth_score: 90,
    data_confidence_score: 75,
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'AI audio research and deployment company. Creators of the most realistic text-to-speech and voice cloning software.',
    category: 'Generative Media',
    funding_total: 101000000,
    employee_count: 60,
    founded_year: 2022,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/elevenlabs.io',
    website: 'https://elevenlabs.io',
    stage: 'Series B',
    is_unicorn: true,
    valuation: 1100000000,
    growth_score: 87,
    data_confidence_score: 85,
  },
  {
    name: 'Runway',
    slug: 'runway',
    description: 'Applied AI research company building the next generation of creative tools for video generation and editing.',
    category: 'Generative Media',
    funding_total: 237000000,
    employee_count: 100,
    founded_year: 2018,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/runwayml.com',
    website: 'https://runwayml.com',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 1500000000,
    growth_score: 85,
    data_confidence_score: 85,
  },
  {
    name: 'Hugging Face',
    slug: 'hugging-face',
    description: 'The AI community building the future. Platform for sharing models, datasets, and ML demos.',
    category: 'MLOps & Tools',
    funding_total: 395000000,
    employee_count: 300,
    founded_year: 2016,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/huggingface.co',
    website: 'https://huggingface.co',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 4500000000,
    growth_score: 82,
    data_confidence_score: 90,
  },
  {
    name: 'Databricks',
    slug: 'databricks',
    description: 'Data and AI company providing a unified analytics platform for data engineering, machine learning, and analytics.',
    category: 'Data & Analytics',
    funding_total: 4000000000,
    employee_count: 6000,
    founded_year: 2013,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/databricks.com',
    website: 'https://databricks.com',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 43000000000,
    growth_score: 78,
    data_confidence_score: 95,
  },
  {
    name: 'xAI',
    slug: 'xai',
    description: 'AI company founded by Elon Musk working on building artificial intelligence to accelerate human scientific discovery.',
    category: 'Foundation Models',
    funding_total: 6000000000,
    employee_count: 100,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/x.ai',
    website: 'https://x.ai',
    stage: 'Series B',
    is_unicorn: true,
    valuation: 24000000000,
    growth_score: 90,
    data_confidence_score: 80,
  },
  {
    name: 'Cohere',
    slug: 'cohere',
    description: 'Enterprise AI platform providing LLMs and NLP tools for businesses to build language understanding into products.',
    category: 'Foundation Models',
    funding_total: 970000000,
    employee_count: 300,
    founded_year: 2019,
    hq_city: 'Toronto',
    hq_country: 'Canada',
    logo_url: 'https://logo.clearbit.com/cohere.com',
    website: 'https://cohere.com',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 5500000000,
    growth_score: 80,
    data_confidence_score: 85,
  },
  {
    name: 'Adept',
    slug: 'adept',
    description: 'ML research and product lab building general intelligence through action transformers.',
    category: 'AI Applications',
    funding_total: 415000000,
    employee_count: 50,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/adept.ai',
    website: 'https://adept.ai',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 82,
    data_confidence_score: 75,
  },
  {
    name: 'Character.ai',
    slug: 'character-ai',
    description: 'AI chatbot platform allowing users to create and interact with AI characters.',
    category: 'Consumer AI',
    funding_total: 193000000,
    employee_count: 80,
    founded_year: 2021,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/character.ai',
    website: 'https://character.ai',
    stage: 'Series A',
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 88,
    data_confidence_score: 80,
  },
  {
    name: 'Stability AI',
    slug: 'stability-ai',
    description: 'Open-source generative AI company behind Stable Diffusion, developing AI models for image, video, audio, and language.',
    category: 'Generative Media',
    funding_total: 101000000,
    employee_count: 200,
    founded_year: 2019,
    hq_city: 'London',
    hq_country: 'UK',
    logo_url: 'https://logo.clearbit.com/stability.ai',
    website: 'https://stability.ai',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 85,
    data_confidence_score: 85,
  },
  {
    name: 'Scale AI',
    slug: 'scale-ai',
    description: 'Data platform for AI providing high-quality training data for machine learning models.',
    category: 'Data & Analytics',
    funding_total: 603000000,
    employee_count: 700,
    founded_year: 2016,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/scale.com',
    website: 'https://scale.com',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 7300000000,
    growth_score: 80,
    data_confidence_score: 90,
  },
  {
    name: 'Weights & Biases',
    slug: 'weights-biases',
    description: 'MLOps platform for experiment tracking, dataset versioning, and model management.',
    category: 'MLOps & Tools',
    funding_total: 250000000,
    employee_count: 200,
    founded_year: 2017,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/wandb.ai',
    website: 'https://wandb.ai',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 1250000000,
    growth_score: 78,
    data_confidence_score: 85,
  },
  {
    name: 'LangChain',
    slug: 'langchain',
    description: 'Framework for developing applications powered by language models.',
    category: 'MLOps & Tools',
    funding_total: 30000000,
    employee_count: 50,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/langchain.com',
    website: 'https://langchain.com',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 200000000,
    growth_score: 85,
    data_confidence_score: 80,
  },
  {
    name: 'Pinecone',
    slug: 'pinecone',
    description: 'Vector database for building accurate, scalable, and high-performance AI applications.',
    category: 'AI Infrastructure',
    funding_total: 138000000,
    employee_count: 100,
    founded_year: 2019,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/pinecone.io',
    website: 'https://pinecone.io',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 750000000,
    growth_score: 82,
    data_confidence_score: 85,
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    description: 'AI video generation platform enabling creation of professional videos from text.',
    category: 'Generative Media',
    funding_total: 156000000,
    employee_count: 200,
    founded_year: 2017,
    hq_city: 'London',
    hq_country: 'UK',
    logo_url: 'https://logo.clearbit.com/synthesia.io',
    website: 'https://synthesia.io',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 80,
    data_confidence_score: 85,
  },
  {
    name: 'Replit',
    slug: 'replit',
    description: 'Collaborative browser-based IDE with AI-powered coding assistance.',
    category: 'AI Applications',
    funding_total: 200000000,
    employee_count: 150,
    founded_year: 2016,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/replit.com',
    website: 'https://replit.com',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 1160000000,
    growth_score: 83,
    data_confidence_score: 85,
  },
  {
    name: 'Glean',
    slug: 'glean',
    description: 'AI-powered workplace search and knowledge discovery platform.',
    category: 'Enterprise AI',
    funding_total: 360000000,
    employee_count: 300,
    founded_year: 2019,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/glean.com',
    website: 'https://glean.com',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 2200000000,
    growth_score: 82,
    data_confidence_score: 85,
  },
  {
    name: 'Sierra',
    slug: 'sierra',
    description: 'Conversational AI platform for businesses to build AI agents for customer experience.',
    category: 'Enterprise AI',
    funding_total: 110000000,
    employee_count: 80,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/sierra.ai',
    website: 'https://sierra.ai',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 88,
    data_confidence_score: 75,
  },
  {
    name: 'Together AI',
    slug: 'together-ai',
    description: 'Cloud platform for running, training, and fine-tuning open-source generative AI models.',
    category: 'AI Infrastructure',
    funding_total: 225000000,
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/together.ai',
    website: 'https://together.ai',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 1250000000,
    growth_score: 85,
    data_confidence_score: 80,
  },
  {
    name: 'Lambda Labs',
    slug: 'lambda-labs',
    description: 'GPU cloud provider for deep learning and AI workloads.',
    category: 'AI Infrastructure',
    funding_total: 480000000,
    employee_count: 150,
    founded_year: 2012,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/lambdalabs.com',
    website: 'https://lambdalabs.com',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 1500000000,
    growth_score: 78,
    data_confidence_score: 85,
  },
  {
    name: 'CoreWeave',
    slug: 'coreweave',
    description: 'Specialized GPU cloud provider for AI/ML workloads.',
    category: 'AI Infrastructure',
    funding_total: 2300000000,
    employee_count: 300,
    founded_year: 2017,
    hq_city: 'Roseland',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/coreweave.com',
    website: 'https://coreweave.com',
    stage: 'Series C',
    is_unicorn: true,
    valuation: 19000000000,
    growth_score: 85,
    data_confidence_score: 85,
  },
  {
    name: 'Cerebras Systems',
    slug: 'cerebras-systems',
    description: 'AI hardware company building the world\'s largest chip for AI compute.',
    category: 'AI Chips & Hardware',
    funding_total: 720000000,
    employee_count: 300,
    founded_year: 2016,
    hq_city: 'Sunnyvale',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/cerebras.net',
    website: 'https://cerebras.net',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 4000000000,
    growth_score: 75,
    data_confidence_score: 90,
  },
  {
    name: 'Groq',
    slug: 'groq',
    description: 'AI semiconductor company building Language Processing Units (LPUs) for fast inference.',
    category: 'AI Chips & Hardware',
    funding_total: 367000000,
    employee_count: 200,
    founded_year: 2016,
    hq_city: 'Mountain View',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/groq.com',
    website: 'https://groq.com',
    stage: 'Series C',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 80,
    data_confidence_score: 85,
  },
  {
    name: 'Poolside',
    slug: 'poolside',
    description: 'AI company building foundation models for software development.',
    category: 'Foundation Models',
    funding_total: 500000000,
    employee_count: 50,
    founded_year: 2023,
    hq_city: 'Paris',
    hq_country: 'France',
    logo_url: 'https://logo.clearbit.com/poolside.ai',
    website: 'https://poolside.ai',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 2000000000,
    growth_score: 85,
    data_confidence_score: 70,
  },
  {
    name: 'Magic',
    slug: 'magic',
    description: 'AI software engineer building autonomous coding agents.',
    category: 'AI Applications',
    funding_total: 515000000,
    employee_count: 40,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/magic.dev',
    website: 'https://magic.ai',
    stage: 'Series B',
    is_unicorn: true,
    valuation: 1500000000,
    growth_score: 88,
    data_confidence_score: 75,
  },
  {
    name: 'Codeium',
    slug: 'codeium',
    description: 'Free AI-powered code completion and chat for developers.',
    category: 'AI Applications',
    funding_total: 93000000,
    employee_count: 80,
    founded_year: 2021,
    hq_city: 'Mountain View',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/codeium.com',
    website: 'https://codeium.com',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 82,
    data_confidence_score: 80,
  },
  {
    name: 'Sourcegraph',
    slug: 'sourcegraph',
    description: 'Code intelligence platform with AI-powered code search and navigation.',
    category: 'AI Applications',
    funding_total: 248000000,
    employee_count: 200,
    founded_year: 2013,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/sourcegraph.com',
    website: 'https://sourcegraph.com',
    stage: 'Series D+',
    is_unicorn: false,
    valuation: 2600000000,
    growth_score: 75,
    data_confidence_score: 85,
  },
  {
    name: 'Tabnine',
    slug: 'tabnine',
    description: 'AI code completion assistant for developers.',
    category: 'AI Applications',
    funding_total: 55000000,
    employee_count: 100,
    founded_year: 2018,
    hq_city: 'Tel Aviv',
    hq_country: 'Israel',
    logo_url: 'https://logo.clearbit.com/tabnine.com',
    website: 'https://tabnine.com',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 400000000,
    growth_score: 78,
    data_confidence_score: 80,
  },
  {
    name: 'MosaicML',
    slug: 'mosaicml',
    description: 'Platform for training and deploying large AI models (acquired by Databricks).',
    category: 'AI Infrastructure',
    funding_total: 64000000,
    employee_count: 60,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/mosaicml.com',
    website: 'https://mosaicml.com',
    stage: 'Acquired',
    is_unicorn: false,
    valuation: 1300000000,
    growth_score: 70,
    data_confidence_score: 85,
  },
  {
    name: 'Modular',
    slug: 'modular',
    description: 'AI infrastructure company building Mojo programming language and MAX platform.',
    category: 'AI Infrastructure',
    funding_total: 130000000,
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'Los Altos',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/modular.com',
    website: 'https://modular.com',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 600000000,
    growth_score: 80,
    data_confidence_score: 75,
  },
  {
    name: 'Imbue',
    slug: 'imbue',
    description: 'AI research company building agents that can reason and code.',
    category: 'Foundation Models',
    funding_total: 220000000,
    employee_count: 50,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/imbue.com',
    website: 'https://imbue.com',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 85,
    data_confidence_score: 75,
  },
  {
    name: 'Contextual AI',
    slug: 'contextual-ai',
    description: 'RAG 2.0 platform for building enterprise AI applications.',
    category: 'Enterprise AI',
    funding_total: 80000000,
    employee_count: 40,
    founded_year: 2023,
    hq_city: 'Mountain View',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/contextual.ai',
    website: 'https://contextual.ai',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 400000000,
    growth_score: 82,
    data_confidence_score: 75,
  },
  {
    name: 'Twelve Labs',
    slug: 'twelve-labs',
    description: 'AI foundation models for video understanding and search.',
    category: 'Foundation Models',
    funding_total: 107000000,
    employee_count: 50,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/twelvelabs.io',
    website: 'https://twelvelabs.io',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 84,
    data_confidence_score: 80,
  },
  {
    name: 'Pika',
    slug: 'pika',
    description: 'AI video generation platform for creative video creation.',
    category: 'Generative Media',
    funding_total: 55000000,
    employee_count: 30,
    founded_year: 2023,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/pika.art',
    website: 'https://pika.art',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 250000000,
    growth_score: 86,
    data_confidence_score: 70,
  },
  {
    name: 'HeyGen',
    slug: 'heygen',
    description: 'AI video generation platform with realistic avatars and lip-sync.',
    category: 'Generative Media',
    funding_total: 60000000,
    employee_count: 80,
    founded_year: 2020,
    hq_city: 'Los Angeles',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/heygen.com',
    website: 'https://heygen.com',
    stage: 'Series A',
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 83,
    data_confidence_score: 75,
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'AI-powered audio and video editing platform.',
    category: 'Generative Media',
    funding_total: 100000000,
    employee_count: 100,
    founded_year: 2017,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/descript.com',
    website: 'https://descript.com',
    stage: 'Series C',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 78,
    data_confidence_score: 85,
  },
  {
    name: 'Notion',
    slug: 'notion',
    description: 'Connected workspace with AI-powered writing, planning, and organization.',
    category: 'Productivity AI',
    funding_total: 343000000,
    employee_count: 500,
    founded_year: 2013,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/notion.so',
    website: 'https://notion.so',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 10000000000,
    growth_score: 80,
    data_confidence_score: 90,
  },
  {
    name: 'Figma',
    slug: 'figma',
    description: 'Collaborative interface design tool with AI-powered features (acquired by Adobe, then unwound).',
    category: 'Productivity AI',
    funding_total: 326000000,
    employee_count: 1000,
    founded_year: 2012,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/figma.com',
    website: 'https://figma.com',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 20000000000,
    growth_score: 75,
    data_confidence_score: 95,
  },
  {
    name: 'Linear',
    slug: 'linear',
    description: 'Issue tracking and project management tool built for high-performance teams.',
    category: 'Productivity AI',
    funding_total: 52000000,
    employee_count: 50,
    founded_year: 2019,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/linear.app',
    website: 'https://linear.app',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 400000000,
    growth_score: 78,
    data_confidence_score: 85,
  },
  {
    name: 'Vercel',
    slug: 'vercel',
    description: 'Platform for frontend developers with AI-powered deployment and optimization.',
    category: 'AI Infrastructure',
    funding_total: 312000000,
    employee_count: 400,
    founded_year: 2015,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/vercel.com',
    website: 'https://vercel.com',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 3250000000,
    growth_score: 78,
    data_confidence_score: 90,
  },
  {
    name: 'Supabase',
    slug: 'supabase',
    description: 'Open-source Firebase alternative with AI-powered database features.',
    category: 'AI Infrastructure',
    funding_total: 196000000,
    employee_count: 150,
    founded_year: 2020,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/supabase.com',
    website: 'https://supabase.com',
    stage: 'Series C',
    is_unicorn: false,
    valuation: 2000000000,
    growth_score: 82,
    data_confidence_score: 90,
  },
  {
    name: 'Prisma',
    slug: 'prisma',
    description: 'Next-generation ORM with AI-assisted database workflows.',
    category: 'AI Infrastructure',
    funding_total: 100000000,
    employee_count: 100,
    founded_year: 2016,
    hq_city: 'Berlin',
    hq_country: 'Germany',
    logo_url: 'https://logo.clearbit.com/prisma.io',
    website: 'https://prisma.io',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 75,
    data_confidence_score: 85,
  },
  {
    name: 'Temporal',
    slug: 'temporal',
    description: 'Durable execution platform for building reliable applications.',
    category: 'AI Infrastructure',
    funding_total: 180000000,
    employee_count: 150,
    founded_year: 2019,
    hq_city: 'Seattle',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/temporal.io',
    website: 'https://temporal.io',
    stage: 'Series C',
    is_unicorn: false,
    valuation: 1500000000,
    growth_score: 78,
    data_confidence_score: 85,
  },
  {
    name: 'Robust Intelligence',
    slug: 'robust-intelligence',
    description: 'AI risk management platform for testing and validating ML models.',
    category: 'Cybersecurity AI',
    funding_total: 60000000,
    employee_count: 80,
    founded_year: 2019,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/robustintelligence.com',
    website: 'https://robustintelligence.com',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 300000000,
    growth_score: 75,
    data_confidence_score: 80,
  },
  {
    name: 'Arthur AI',
    slug: 'arthur-ai',
    description: 'ML monitoring and observability platform.',
    category: 'MLOps & Tools',
    funding_total: 60000000,
    employee_count: 60,
    founded_year: 2018,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/arthur.ai',
    website: 'https://arthur.ai',
    stage: 'Series B',
    is_unicorn: false,
    valuation: 250000000,
    growth_score: 72,
    data_confidence_score: 80,
  },
  {
    name: 'Snorkel AI',
    slug: 'snorkel-ai',
    description: 'Data-centric AI platform for programmatic labeling and data development.',
    category: 'Data & Analytics',
    funding_total: 135000000,
    employee_count: 100,
    founded_year: 2019,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/snorkel.ai',
    website: 'https://snorkel.ai',
    stage: 'Series C',
    is_unicorn: false,
    valuation: 1000000000,
    growth_score: 78,
    data_confidence_score: 85,
  },
  {
    name: 'Hugging Face',
    slug: 'hugging-face-2',
    description: 'The AI community building the future. Platform for sharing models, datasets, and ML demos.',
    category: 'MLOps & Tools',
    funding_total: 395000000,
    employee_count: 300,
    founded_year: 2016,
    hq_city: 'New York',
    hq_country: 'USA',
    logo_url: 'https://logo.clearbit.com/huggingface.co',
    website: 'https://huggingface.co',
    stage: 'Series D+',
    is_unicorn: true,
    valuation: 4500000000,
    growth_score: 82,
    data_confidence_score: 90,
  },
];

const investors = [
  {
    name: 'Sequoia Capital',
    slug: 'sequoia-capital',
    type: 'VC',
    bio: 'Legendary venture capital firm backing founders from day one to IPO and beyond. Early investors in Apple, Google, WhatsApp, and many AI companies.',
    aum: 85000000000,
    portfolio_count: 1500,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C', 'Series D+'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'FinTech', 'Healthcare'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/sequoiacap.com',
    avg_check_size: 50000000,
    fund_number: 25,
  },
  {
    name: 'Andreessen Horowitz (a16z)',
    slug: 'andreessen-horowitz',
    type: 'VC',
    bio: 'Venture capital firm investing in software, crypto, bio, and AI. Known for large funds and operator-focused approach.',
    aum: 42000000000,
    portfolio_count: 800,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C', 'Series D+'],
    sector_focus: ['AI/ML', 'Infrastructure', 'Developer Tools', 'Crypto', 'Bio'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/a16z.com',
    avg_check_size: 25000000,
    fund_number: 10,
  },
  {
    name: 'Lightspeed Venture Partners',
    slug: 'lightspeed-venture-partners',
    type: 'VC',
    bio: 'Multi-stage venture capital firm focused on accelerating disruptive innovations and trends in Enterprise, Consumer, and Health.',
    aum: 25000000000,
    portfolio_count: 600,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'FinTech'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/lsvp.com',
    avg_check_size: 15000000,
    fund_number: 15,
  },
  {
    name: 'Khosla Ventures',
    slug: 'khosla-ventures',
    type: 'VC',
    bio: 'Venture capital firm founded by Vinod Khosla focusing on science-based technology ventures including AI, climate, and bio.',
    aum: 15000000000,
    portfolio_count: 500,
    stage_focus: ['Seed', 'Series A', 'Series B'],
    sector_focus: ['AI/ML', 'Climate', 'Bio', 'Enterprise', 'Robotics'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/khoslaventures.com',
    avg_check_size: 10000000,
    fund_number: 8,
  },
  {
    name: 'Accel',
    slug: 'accel',
    type: 'VC',
    bio: 'Global venture capital firm partnering with exceptional founders from inception to IPO.',
    aum: 20000000000,
    portfolio_count: 700,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'SaaS', 'Security'],
    location: 'Palo Alto, CA',
    logo_url: 'https://logo.clearbit.com/accel.com',
    avg_check_size: 10000000,
    fund_number: 16,
  },
  {
    name: 'General Catalyst',
    slug: 'general-catalyst',
    type: 'VC',
    bio: 'Venture capital firm investing in powerful, positive change that endures. Strong focus on AI and frontier tech.',
    aum: 30000000000,
    portfolio_count: 800,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C', 'Series D+'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'Healthcare', 'Climate'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/generalcatalyst.com',
    avg_check_size: 20000000,
    fund_number: 12,
  },
  {
    name: 'Coatue Management',
    slug: 'coatue-management',
    type: 'VC',
    bio: 'Technology-focused investment firm investing in public and private markets.',
    aum: 50000000000,
    portfolio_count: 300,
    stage_focus: ['Series A', 'Series B', 'Series C', 'Series D+'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'FinTech'],
    location: 'New York, NY',
    logo_url: 'https://logo.clearbit.com/coatue.com',
    avg_check_size: 50000000,
    fund_number: 8,
  },
  {
    name: 'Tiger Global Management',
    slug: 'tiger-global',
    type: 'VC',
    bio: 'Global investment firm deploying capital across public and private markets with a focus on internet and technology.',
    aum: 100000000000,
    portfolio_count: 500,
    stage_focus: ['Series B', 'Series C', 'Series D+'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'FinTech', 'SaaS'],
    location: 'New York, NY',
    logo_url: 'https://logo.clearbit.com/tigerglobal.com',
    avg_check_size: 100000000,
    fund_number: 14,
  },
  {
    name: 'Greylock Partners',
    slug: 'greylock-partners',
    type: 'VC',
    bio: 'Venture capital firm partnering with entrepreneurs from the earliest stages to build transformational companies.',
    aum: 15000000000,
    portfolio_count: 400,
    stage_focus: ['Seed', 'Series A', 'Series B'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'Crypto', 'Infrastructure'],
    location: 'Menlo Park, CA',
    logo_url: 'https://logo.clearbit.com/greylock.com',
    avg_check_size: 10000000,
    fund_number: 18,
  },
  {
    name: 'Benchmark',
    slug: 'benchmark',
    type: 'VC',
    bio: 'Venture capital firm with a focus on early-stage investments. Known for a small, high-conviction portfolio.',
    aum: 5000000000,
    portfolio_count: 100,
    stage_focus: ['Seed', 'Series A'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'Marketplace'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/benchmark.com',
    avg_check_size: 5000000,
    fund_number: 12,
  },
  {
    name: 'Index Ventures',
    slug: 'index-ventures',
    type: 'VC',
    bio: 'Venture capital firm backing bold entrepreneurs building transformative companies across Europe, US, and Israel.',
    aum: 12000000000,
    portfolio_count: 300,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'FinTech', 'Climate'],
    location: 'London, UK / San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/indexventures.com',
    avg_check_size: 15000000,
    fund_number: 13,
  },
  {
    name: 'NVentures (NVIDIA)',
    slug: 'nventures',
    type: 'Corporate',
    bio: 'NVIDIA\'s venture capital arm investing in AI startups building on NVIDIA technology.',
    aum: 5000000000,
    portfolio_count: 100,
    stage_focus: ['Seed', 'Series A', 'Series B'],
    sector_focus: ['AI/ML', 'AI Chips', 'Robotics', 'Healthcare AI', 'Autonomous Vehicles'],
    location: 'Santa Clara, CA',
    logo_url: 'https://logo.clearbit.com/nvidia.com',
    avg_check_size: 5000000,
    fund_number: 3,
  },
  {
    name: 'GV (Google Ventures)',
    slug: 'gv',
    type: 'Corporate',
    bio: 'Venture capital arm of Alphabet investing in early and growth-stage technology companies.',
    aum: 8000000000,
    portfolio_count: 500,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'Healthcare', 'Climate'],
    location: 'Mountain View, CA',
    logo_url: 'https://logo.clearbit.com/gv.com',
    avg_check_size: 10000000,
    fund_number: 10,
  },
  {
    name: 'Microsoft M12',
    slug: 'm12',
    type: 'Corporate',
    bio: 'Microsoft\'s venture fund investing in early-stage B2B startups.',
    aum: 3000000000,
    portfolio_count: 200,
    stage_focus: ['Seed', 'Series A', 'Series B'],
    sector_focus: ['AI/ML', 'Enterprise', 'Developer Tools', 'Security', 'Cloud'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/m12.vc',
    avg_check_size: 5000000,
    fund_number: 4,
  },
  {
    name: 'Salesforce Ventures',
    slug: 'salesforce-ventures',
    type: 'Corporate',
    bio: 'Salesforce\'s strategic investment arm investing in enterprise cloud startups.',
    aum: 5000000000,
    portfolio_count: 400,
    stage_focus: ['Series A', 'Series B', 'Series C'],
    sector_focus: ['AI/ML', 'Enterprise', 'SaaS', 'Data', 'Developer Tools'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/salesforce.com',
    avg_check_size: 10000000,
    fund_number: 8,
  },
  {
    name: 'Elad Gil',
    slug: 'elad-gil',
    type: 'Angel',
    bio: 'Prominent angel investor and advisor in AI, crypto, and bio. Early investor in Airbnb, Stripe, Coinbase, and many AI companies.',
    aum: 500000000,
    portfolio_count: 200,
    stage_focus: ['Seed', 'Series A'],
    sector_focus: ['AI/ML', 'Crypto', 'Bio', 'Developer Tools'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/eladgil.com',
    avg_check_size: 1000000,
    fund_number: 1,
  },
  {
    name: 'Nat Friedman',
    slug: 'nat-friedman',
    type: 'Angel',
    bio: 'Former GitHub CEO, active angel investor in AI and developer tools.',
    aum: 300000000,
    portfolio_count: 150,
    stage_focus: ['Seed', 'Series A'],
    sector_focus: ['AI/ML', 'Developer Tools', 'Open Source'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/nat.dev',
    avg_check_size: 500000,
    fund_number: 1,
  },
  {
    name: 'Daniel Gross',
    slug: 'daniel-gross',
    type: 'Angel',
    bio: 'Founder of Pioneer, former YC partner, active angel investor in AI startups.',
    aum: 200000000,
    portfolio_count: 100,
    stage_focus: ['Pre-Seed', 'Seed'],
    sector_focus: ['AI/ML', 'Developer Tools', 'Consumer AI'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/pioneer.app',
    avg_check_size: 250000,
    fund_number: 1,
  },
  {
    name: 'SV Angel',
    slug: 'sv-angel',
    type: 'Angel',
    bio: 'Seed-stage venture firm founded by Ron Conway, one of Silicon Valley\'s most prolific angel investors.',
    aum: 1000000000,
    portfolio_count: 1000,
    stage_focus: ['Pre-Seed', 'Seed'],
    sector_focus: ['AI/ML', 'Consumer', 'Enterprise', 'FinTech'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/svangel.com',
    avg_check_size: 500000,
    fund_number: 5,
  },
  {
    name: 'Founders Fund',
    slug: 'founders-fund',
    type: 'VC',
    bio: 'Venture capital firm founded by Peter Thiel investing in revolutionary technologies.',
    aum: 12000000000,
    portfolio_count: 200,
    stage_focus: ['Seed', 'Series A', 'Series B', 'Series C', 'Series D+'],
    sector_focus: ['AI/ML', 'Space', 'Bio', 'FinTech', 'Defense'],
    location: 'San Francisco, CA',
    logo_url: 'https://logo.clearbit.com/foundersfund.com',
    avg_check_size: 20000000,
    fund_number: 8,
  },
  {
    name: 'Thrive Capital',
    slug: 'thrive-capital',
    type: 'VC',
    bio: 'Venture capital firm investing in internet, software, and technology companies.',
    aum: 20000000000,
    portfolio_count: 150,
    stage_focus: ['Series A', 'Series B', 'Series C', 'Series D+'],
    sector_focus: ['AI/ML', 'Enterprise', 'Consumer', 'FinTech'],
    location: 'New York, NY',
    logo_url: 'https://logo.clearbit.com/thrivecap.com',
    avg_check_size: 50000000,
    fund_number: 10,
  },
];

const fundingRounds = [
  { company_slug: 'openai', round_type: 'Series A', amount: 1000000000, currency: 'USD', date: '2019-07-22', lead_investor_slug: 'microsoft-m12' },
  { company_slug: 'openai', round_type: 'Series B', amount: 10000000000, currency: 'USD', date: '2023-01-23', lead_investor_slug: 'microsoft-m12' },
  { company_slug: 'anthropic', round_type: 'Series A', amount: 124000000, currency: 'USD', date: '2021-05-26', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'anthropic', round_type: 'Series B', amount: 580000000, currency: 'USD', date: '2022-04-27', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'anthropic', round_type: 'Series C', amount: 450000000, currency: 'USD', date: '2023-05-23', lead_investor_slug: 'google-ventures' },
  { company_slug: 'perplexity-ai', round_type: 'Series A', amount: 25000000, currency: 'USD', date: '2023-03-28', lead_investor_slug: 'new-enterprise-associates' },
  { company_slug: 'perplexity-ai', round_type: 'Series B', amount: 73600000, currency: 'USD', date: '2024-01-04', lead_investor_slug: 'institutional-venture-partners' },
  { company_slug: 'mistral-ai', round_type: 'Seed', amount: 113000000, currency: 'USD', date: '2023-06-13', lead_investor_slug: 'lightspeed-venture-partners' },
  { company_slug: 'mistral-ai', round_type: 'Series A', amount: 415000000, currency: 'USD', date: '2023-12-11', lead_investor_slug: 'andreessen-horowitz' },
  { company_slug: 'cursor', round_type: 'Seed', amount: 8000000, currency: 'USD', date: '2022-10-15', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'cursor', round_type: 'Series A', amount: 60000000, currency: 'USD', date: '2023-08-15', lead_investor_slug: 'andreessen-horowitz' },
  { company_slug: 'elevenlabs', round_type: 'Seed', amount: 2000000, currency: 'USD', date: '2022-05-15', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'elevenlabs', round_type: 'Series A', amount: 19000000, currency: 'USD', date: '2023-06-20', lead_investor_slug: 'andreessen-horowitz' },
  { company_slug: 'elevenlabs', round_type: 'Series B', amount: 80000000, currency: 'USD', date: '2024-01-22', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'runway', round_type: 'Series A', amount: 50000000, currency: 'USD', date: '2022-12-15', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'runway', round_type: 'Series B', amount: 50000000, currency: 'USD', date: '2023-06-29', lead_investor_slug: 'google-ventures' },
  { company_slug: 'runway', round_type: 'Series C', amount: 141000000, currency: 'USD', date: '2023-12-19', lead_investor_slug: 'general-catalyst' },
  { company_slug: 'hugging-face', round_type: 'Series A', amount: 15000000, currency: 'USD', date: '2019-10-15', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'hugging-face', round_type: 'Series B', amount: 40000000, currency: 'USD', date: '2021-03-15', lead_investor_slug: 'lux-capital' },
  { company_slug: 'hugging-face', round_type: 'Series C', amount: 100000000, currency: 'USD', date: '2022-05-09', lead_investor_slug: 'coatue-management' },
  { company_slug: 'databricks', round_type: 'Series A', amount: 13000000, currency: 'USD', date: '2014-06-15', lead_investor_slug: 'andreessen-horowitz' },
  { company_slug: 'databricks', round_type: 'Series B', amount: 33000000, currency: 'USD', date: '2015-11-10', lead_investor_slug: 'new-enterprise-associates' },
  { company_slug: 'databricks', round_type: 'Series C', amount: 60000000, currency: 'USD', date: '2017-05-10', lead_investor_slug: 'battery-ventures' },
  { company_slug: 'databricks', round_type: 'Series D', amount: 140000000, currency: 'USD', date: '2019-02-05', lead_investor_slug: 'andreessen-horowitz' },
  { company_slug: 'databricks', round_type: 'Series E', amount: 400000000, currency: 'USD', date: '2021-02-01', lead_investor_slug: 'counterpoint-global' },
  { company_slug: 'databricks', round_type: 'Series F', amount: 1000000000, currency: 'USD', date: '2021-08-31', lead_investor_slug: 'franklin-templeton' },
  { company_slug: 'xai', round_type: 'Series A', amount: 1000000000, currency: 'USD', date: '2023-07-15', lead_investor_slug: 'sequoia-capital' },
  { company_slug: 'xai', round_type: 'Series B', amount: 6000000000, currency: 'USD', date: '2024-05-26', lead_investor_slug: 'andreessen-horowitz' },
  { company_slug: 'cohere', round_type: 'Series A', amount: 40000000, currency: 'USD', date: '2021-09-15', lead_investor_slug: 'index-ventures' },
  { company_slug: 'cohere', round_type: 'Series B', amount: 125000000, currency: 'USD', date: '2022-02-15', lead_investor_slug: 'tiger-global' },
  { company_slug: 'cohere', round_type: 'Series C', amount: 270000000, currency: 'USD', date: '2023-06-08', lead_investor_slug: 'inovia-capital' },
  { company_slug: 'adept', round_type: 'Series A', amount: 65000000, currency: 'USD', date: '2022-04-26', lead_investor_slug: 'greylock-partners' },
  { company_slug: 'adept', round_type: 'Series B', amount: 350000000, currency: 'USD', date: '2023-03-14', lead_investor_slug: 'general-catalyst' },
  { company_slug: 'character-ai', round_type: 'Series A', amount: 150000000, currency: 'USD', date: '2023-03-23', lead_investor_slug: 'andreessen-horowitz' },
  { company_slug: 'stability-ai', round_type: 'Seed', amount: 10000000, currency: 'USD', date: '2022-10-15', lead_investor_slug: 'coatue-management' },
  { company_slug: 'stability-ai', round_type: 'Series A', amount: 101000000, currency: 'USD', date: '2022-10-17', lead_investor_slug: 'lightspeed-venture-partners' },
  { company_slug: 'scale-ai', round_type: 'Series A', amount: 18000000, currency: 'USD', date: '2019-08-15', lead_investor_slug: 'index-ventures' },
  { company_slug: 'scale-ai', round_type: 'Series B', amount: 100000000, currency: 'USD', date: '2020-08-15', lead_investor_slug: 'founders-fund' },
  { company_slug: 'scale-ai', round_type: 'Series C', amount: 155000000, currency: 'USD', date: '2021-04-15', lead_investor_slug: 'tiger-global' },
  { company_slug: 'scale-ai', round_type: 'Series D', amount: 325000000, currency: 'USD', date: '2022-05-15', lead_investor_slug: 'coatue-management' },
];

const founders = [
  { name: 'Sam Altman', slug: 'sam-altman', title: 'CEO', company_slug: 'openai', bio: 'CEO of OpenAI, former president of Y Combinator.', twitter: 'sama', linkedin: 'https://linkedin.com/in/sama', location: 'San Francisco, CA' },
  { name: 'Greg Brockman', slug: 'greg-brockman', title: 'President & Co-founder', company_slug: 'openai', bio: 'President and co-founder of OpenAI, former CTO of Stripe.', twitter: 'gdb', linkedin: 'https://linkedin.com/in/gdb', location: 'San Francisco, CA' },
  { name: 'Ilya Sutskever', slug: 'ilya-sutskever', title: 'Chief Scientist & Co-founder', company_slug: 'openai', bio: 'Co-founder and Chief Scientist at OpenAI.', twitter: 'ilyasut', linkedin: 'https://linkedin.com/in/ilyasut', location: 'San Francisco, CA' },
  { name: 'Dario Amodei', slug: 'dario-amodei', title: 'CEO & Co-founder', company_slug: 'anthropic', bio: 'CEO and co-founder of Anthropic, former VP of Research at OpenAI.', twitter: 'darioamodei', linkedin: 'https://linkedin.com/in/darioamodei', location: 'San Francisco, CA' },
  { name: 'Daniela Amodei', slug: 'daniela-amodei', title: 'President & Co-founder', company_slug: 'anthropic', bio: 'President and co-founder of Anthropic, former VP of Safety and Policy at OpenAI.', twitter: 'daniela_amodei', linkedin: 'https://linkedin.com/in/daniela-amodei', location: 'San Francisco, CA' },
  { name: 'Aravind Srinivas', slug: 'aravind-srinivas', title: 'CEO & Co-founder', company_slug: 'perplexity-ai', bio: 'CEO and co-founder of Perplexity AI, former research scientist at OpenAI.', twitter: 'AravSrinivas', linkedin: 'https://linkedin.com/in/aravindsrinivas', location: 'San Francisco, CA' },
  { name: 'Arthur Mensch', slug: 'arthur-mensch', title: 'CEO & Co-founder', company_slug: 'mistral-ai', bio: 'CEO and co-founder of Mistral AI, former research scientist at DeepMind.', twitter: 'arthurmensch', linkedin: 'https://linkedin.com/in/arthur-mensch', location: 'Paris, France' },
  { name: 'Guillaume Lample', slug: 'guillaume-lample', title: 'Chief Scientist & Co-founder', company_slug: 'mistral-ai', bio: 'Co-founder and Chief Scientist at Mistral AI.', twitter: 'guillaumelample', linkedin: 'https://linkedin.com/in/guillaumelample', location: 'Paris, France' },
  { name: 'Michael Truell', slug: 'michael-truell', title: 'CEO & Co-founder', company_slug: 'cursor', bio: 'CEO and co-founder of Cursor, building the AI-first code editor.', twitter: 'michaeltruell', linkedin: 'https://linkedin.com/in/michaeltruell', location: 'San Francisco, CA' },
  { name: 'David Holz', slug: 'david-holz', title: 'Founder & CEO', company_slug: 'midjourney', bio: 'Founder of Midjourney, former researcher at NASA and Max Planck Institute.', twitter: 'davidholzmj', linkedin: 'https://linkedin.com/in/davidholz', location: 'San Francisco, CA' },
  { name: 'Mati Staniszewski', slug: 'mati-staniszewski', title: 'CEO & Co-founder', company_slug: 'elevenlabs', bio: 'CEO and co-founder of ElevenLabs, former Palantir.', twitter: 'matistaniszewski', linkedin: 'https://linkedin.com/in/matistaniszewski', location: 'New York, NY' },
  { name: 'Piotr Dabkowski', slug: 'piotr-dabkowski', title: 'CTO & Co-founder', company_slug: 'elevenlabs', bio: 'CTO and co-founder of ElevenLabs, former Google.', twitter: 'piotrdabkowski', linkedin: 'https://linkedin.com/in/piotrdabkowski', location: 'New York, NY' },
  { name: 'Cristóbal Valenzuela', slug: 'cristobal-valenzuela', title: 'CEO & Co-founder', company_slug: 'runway', bio: 'CEO and co-founder of Runway, building creative AI tools.', twitter: 'cvalenzuela', linkedin: 'https://linkedin.com/in/cvalenzuela', location: 'New York, NY' },
  { name: 'Alejandro Matamala', slug: 'alejandro-matamala', title: 'COO & Co-founder', company_slug: 'runway', bio: 'COO and co-founder of Runway.', twitter: 'alejomatamala', linkedin: 'https://linkedin.com/in/alejomatamala', location: 'New York, NY' },
  { name: 'Clement Delangue', slug: 'clement-delangue', title: 'CEO & Co-founder', company_slug: 'hugging-face', bio: 'CEO and co-founder of Hugging Face.', twitter: 'clemdelangue', linkedin: 'https://linkedin.com/in/clemdelangue', location: 'New York, NY' },
  { name: 'Ali Ghodsi', slug: 'ali-ghodsi', title: 'CEO & Co-founder', company_slug: 'databricks', bio: 'CEO and co-founder of Databricks, creator of Apache Spark.', twitter: 'alighodsi', linkedin: 'https://linkedin.com/in/alighodsi', location: 'San Francisco, CA' },
  { name: 'Elon Musk', slug: 'elon-musk', title: 'Founder', company_slug: 'xai', bio: 'Founder of xAI, CEO of Tesla and SpaceX.', twitter: 'elonmusk', linkedin: 'https://linkedin.com/in/elonmusk', location: 'San Francisco, CA' },
  { name: 'Aidan Gomez', slug: 'aidan-gomez', title: 'CEO & Co-founder', company_slug: 'cohere', bio: 'CEO and co-founder of Cohere, co-author of "Attention Is All You Need".', twitter: 'aidan_gomez', linkedin: 'https://linkedin.com/in/aidangomez', location: 'Toronto, Canada' },
  { name: 'David Luan', slug: 'david-luan', title: 'CEO & Co-founder', company_slug: 'adept', bio: 'CEO and co-founder of Adept, former OpenAI and Google.', twitter: 'davidluan', linkedin: 'https://linkedin.com/in/davidluan', location: 'San Francisco, CA' },
  { name: 'Noam Shazeer', slug: 'noam-shazeer', title: 'CEO & Co-founder', company_slug: 'character-ai', bio: 'CEO and co-founder of Character.AI, co-author of "Attention Is All You Need".', twitter: 'noamshazeer', linkedin: 'https://linkedin.com/in/noamshazeer', location: 'Palo Alto, CA' },
  { name: 'Emad Mostaque', slug: 'emad-mostaque', title: 'Founder', company_slug: 'stability-ai', bio: 'Founder of Stability AI.', twitter: 'emadmostaque', linkedin: 'https://linkedin.com/in/emadmostaque', location: 'London, UK' },
  { name: 'Alexandr Wang', slug: 'alexandr-wang', title: 'CEO & Founder', company_slug: 'scale-ai', bio: 'CEO and founder of Scale AI.', twitter: 'alexandr_wang', linkedin: 'https://linkedin.com/in/alexandrwang', location: 'San Francisco, CA' },
];

const products = [
  { company_slug: 'openai', name: 'GPT-4', description: 'Most capable multimodal model from OpenAI', category: 'Foundation Model', launch_date: '2023-03-14', upvotes: 15000, website_url: 'https://openai.com/gpt-4' },
  { company_slug: 'openai', name: 'ChatGPT', description: 'Conversational AI assistant', category: 'Chat', launch_date: '2022-11-30', upvotes: 50000, website_url: 'https://chat.openai.com' },
  { company_slug: 'openai', name: 'DALL-E 3', description: 'Advanced image generation model', category: 'Image Generation', launch_date: '2023-09-20', upvotes: 25000, website_url: 'https://openai.com/dall-e-3' },
  { company_slug: 'openai', name: 'Whisper', description: 'Automatic speech recognition system', category: 'Speech Recognition', launch_date: '2022-09-21', upvotes: 12000, website_url: 'https://openai.com/whisper' },
  { company_slug: 'openai', name: 'Sora', description: 'Text-to-video generation model', category: 'Video Generation', launch_date: '2024-02-15', upvotes: 30000, website_url: 'https://openai.com/sora' },
  { company_slug: 'anthropic', name: 'Claude 3 Opus', description: 'Most intelligent Claude model', category: 'Foundation Model', launch_date: '2024-03-04', upvotes: 18000, website_url: 'https://claude.ai' },
  { company_slug: 'anthropic', name: 'Claude 3 Sonnet', description: 'Balanced intelligence and speed', category: 'Foundation Model', launch_date: '2024-03-04', upvotes: 15000, website_url: 'https://claude.ai' },
  { company_slug: 'anthropic', name: 'Claude 3 Haiku', description: 'Fastest and most cost-effective model', category: 'Foundation Model', launch_date: '2024-03-13', upvotes: 10000, website_url: 'https://claude.ai' },
  { company_slug: 'perplexity-ai', name: 'Perplexity Pro', description: 'AI-powered search with GPT-4 and Claude', category: 'Search', launch_date: '2023-01-15', upvotes: 20000, website_url: 'https://perplexity.ai/pro' },
  { company_slug: 'perplexity-ai', name: 'Perplexity Copilot', description: 'Interactive guided search', category: 'Search', launch_date: '2023-06-15', upvotes: 12000, website_url: 'https://perplexity.ai/copilot' },
  { company_slug: 'mistral-ai', name: 'Mistral Large', description: 'Flagship commercial model', category: 'Foundation Model', launch_date: '2024-02-26', upvotes: 8000, website_url: 'https://mistral.ai' },
  { company_slug: 'mistral-ai', name: 'Mixtral 8x7B', description: 'Open-weight mixture of experts model', category: 'Foundation Model', launch_date: '2023-12-11', upvotes: 15000, website_url: 'https://mistral.ai' },
  { company_slug: 'mistral-ai', name: 'Mistral 7B', description: 'Open-weight 7B parameter model', category: 'Foundation Model', launch_date: '2023-09-27', upvotes: 25000, website_url: 'https://mistral.ai' },
  { company_slug: 'cursor', name: 'Cursor', description: 'AI-first code editor', category: 'Code Editor', launch_date: '2023-03-15', upvotes: 30000, website_url: 'https://cursor.sh' },
  { company_slug: 'midjourney', name: 'Midjourney v6', description: 'Advanced AI image generation', category: 'Image Generation', launch_date: '2023-12-21', upvotes: 40000, website_url: 'https://midjourney.com' },
  { company_slug: 'elevenlabs', name: 'ElevenLabs Voice AI', description: 'Realistic text-to-speech and voice cloning', category: 'Voice AI', launch_date: '2023-01-15', upvotes: 22000, website_url: 'https://elevenlabs.io' },
  { company_slug: 'elevenlabs', name: 'Voice Library', description: 'Community voice sharing platform', category: 'Voice AI', launch_date: '2023-08-15', upvotes: 10000, website_url: 'https://elevenlabs.io/voice-library' },
  { company_slug: 'runway', name: 'Gen-2', description: 'Text-to-video generation', category: 'Video Generation', launch_date: '2023-06-15', upvotes: 20000, website_url: 'https://runwayml.com/gen-2' },
  { company_slug: 'runway', name: 'Gen-1', description: 'Video-to-video generation', category: 'Video Generation', launch_date: '2023-02-01', upvotes: 15000, website_url: 'https://runwayml.com/gen-1' },
  { company_slug: 'hugging-face', name: 'Transformers', description: 'State-of-the-art NLP library', category: 'ML Library', launch_date: '2019-10-15', upvotes: 50000, website_url: 'https://github.com/huggingface/transformers' },
  { company_slug: 'hugging-face', name: 'Hugging Face Hub', description: 'Platform for sharing models and datasets', category: 'ML Platform', launch_date: '2020-03-15', upvotes: 40000, website_url: 'https://huggingface.co' },
  { company_slug: 'hugging-face', name: 'Gradio', description: 'Build ML web apps in Python', category: 'ML Tools', launch_date: '2021-06-15', upvotes: 25000, website_url: 'https://gradio.app' },
  { company_slug: 'databricks', name: 'Databricks Lakehouse', description: 'Unified data analytics platform', category: 'Data Platform', launch_date: '2020-01-15', upvotes: 10000, website_url: 'https://databricks.com/product/lakehouse' },
  { company_slug: 'databricks', name: 'MLflow', description: 'Open-source ML lifecycle platform', category: 'MLOps', launch_date: '2018-06-15', upvotes: 20000, website_url: 'https://mlflow.org' },
  { company_slug: 'xai', name: 'Grok', description: 'Conversational AI with real-time knowledge', category: 'Chat', launch_date: '2023-11-04', upvotes: 12000, website_url: 'https://x.ai/grok' },
  { company_slug: 'cohere', name: 'Command R+', description: 'Enterprise-grade LLM for RAG', category: 'Foundation Model', launch_date: '2024-04-04', upvotes: 5000, website_url: 'https://cohere.com' },
  { company_slug: 'cohere', name: 'Embed', description: 'Text embeddings for search and classification', category: 'Embeddings', launch_date: '2022-06-15', upvotes: 8000, website_url: 'https://cohere.com/embed' },
  { company_slug: 'adept', name: 'ACT-1', description: 'Action transformer for computer use', category: 'AI Agent', launch_date: '2022-09-15', upvotes: 8000, website_url: 'https://adept.ai' },
  { company_slug: 'character-ai', name: 'Character.AI', description: 'AI chatbot platform with characters', category: 'Chat', launch_date: '2022-09-16', upvotes: 35000, website_url: 'https://character.ai' },
  { company_slug: 'stability-ai', name: 'Stable Diffusion XL', description: 'Open-source image generation', category: 'Image Generation', launch_date: '2023-07-26', upvotes: 45000, website_url: 'https://stability.ai/stable-diffusion' },
  { company_slug: 'stability-ai', name: 'Stable Video Diffusion', description: 'Open-source video generation', category: 'Video Generation', launch_date: '2023-11-21', upvotes: 18000, website_url: 'https://stability.ai/stable-video' },
  { company_slug: 'scale-ai', name: 'Scale Data Engine', description: 'Data labeling and annotation platform', category: 'Data Platform', launch_date: '2018-01-15', upvotes: 5000, website_url: 'https://scale.com/products/data-engine' },
  { company_slug: 'cursor', name: 'Cursor Chat', description: 'AI chat in your editor', category: 'Code Assistant', launch_date: '2023-05-15', upvotes: 15000, website_url: 'https://cursor.sh/features/chat' },
  { company_slug: 'cursor', name: 'Cursor Composer', description: 'Multi-file AI coding agent', category: 'Code Assistant', launch_date: '2024-01-15', upvotes: 12000, website_url: 'https://cursor.sh/features/composer' },
  { company_slug: 'runway', name: 'Gen-3 Alpha', description: 'Next-gen video generation', category: 'Video Generation', launch_date: '2024-06-15', upvotes: 25000, website_url: 'https://runwayml.com/gen-3' },
];

const newsArticles = [
  { title: 'OpenAI Announces GPT-4 Turbo with 128K Context Window', url: 'https://openai.com/blog/gpt-4-turbo', published_at: '2024-01-15T10:00:00Z', source: 'OpenAI Blog', tag: 'Launch', related_company_slugs: ['openai'], summary: 'OpenAI releases GPT-4 Turbo with improved performance, lower pricing, and 128K context window.' },
  { title: 'Anthropic Launches Claude 3 Family: Opus, Sonnet, Haiku', url: 'https://anthropic.com/news/claude-3-family', published_at: '2024-03-04T10:00:00Z', source: 'Anthropic Blog', tag: 'Launch', related_company_slugs: ['anthropic'], summary: 'Anthropic introduces three new models with varying capabilities and price points.' },
  { title: 'Mistral AI Raises €385M Series A at $2B Valuation', url: 'https://techcrunch.com/2023/12/11/mistral-ai-series-a', published_at: '2023-12-11T14:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['mistral-ai'], summary: 'European AI startup Mistral AI closes massive Series A led by Andreessen Horowitz.' },
  { title: 'Perplexity AI Raises $73.6M Series B Led by IVP', url: 'https://techcrunch.com/2024/01/04/perplexity-series-b', published_at: '2024-01-04T12:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['perplexity-ai'], summary: 'Answer engine Perplexity AI reaches unicorn status with new funding.' },
  { title: 'ElevenLabs Becomes Unicorn with $80M Series B', url: 'https://techcrunch.com/2024/01/22/elevenlabs-series-b', published_at: '2024-01-22T10:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['elevenlabs'], summary: 'Voice AI startup ElevenLabs raises Series B at $1.1B valuation led by Sequoia.' },
  { title: 'Runway Announces Gen-3 Alpha Video Model', url: 'https://runwayml.com/blog/gen-3-alpha', published_at: '2024-06-15T10:00:00Z', source: 'Runway Blog', tag: 'Launch', related_company_slugs: ['runway'], summary: 'Runway unveils Gen-3 Alpha, a new frontier for high-fidelity video generation.' },
  { title: 'xAI Raises $6B Series B at $24B Valuation', url: 'https://techcrunch.com/2024/05/26/xai-series-b', published_at: '2024-05-26T15:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['xai'], summary: 'Elon Musk\'s xAI raises massive Series B from Sequoia, a16z, and others.' },
  { title: 'Hugging Face Hits $4.5B Valuation in Series D', url: 'https://techcrunch.com/2023/08/15/hugging-face-series-d', published_at: '2023-08-15T11:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['hugging-face'], summary: 'Hugging Face raises $235M Series D led by Salesforce, Google, NVIDIA.' },
  { title: 'Databricks Acquires MosaicML for $1.3B', url: 'https://databricks.com/blog/2023/06/26/databricks-acquires-mosaicml', published_at: '2023-06-26T10:00:00Z', source: 'Databricks Blog', tag: 'Acquisition', related_company_slugs: ['databricks', 'mosaicml'], summary: 'Databricks acquires MosaicML to strengthen generative AI capabilities.' },
  { title: 'Scale AI Raises $325M Series D at $7.3B Valuation', url: 'https://techcrunch.com/2022/05/15/scale-ai-series-d', published_at: '2022-05-15T10:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['scale-ai'], summary: 'Data labeling platform Scale AI raises massive Series D round.' },
  { title: 'Cohere Launches Command R+ for Enterprise RAG', url: 'https://cohere.com/blog/command-r-plus', published_at: '2024-04-04T10:00:00Z', source: 'Cohere Blog', tag: 'Launch', related_company_slugs: ['cohere'], summary: 'Cohere releases Command R+, optimized for enterprise retrieval-augmented generation.' },
  { title: 'Stability AI Releases Stable Video Diffusion', url: 'https://stability.ai/blog/stable-video-diffusion', published_at: '2023-11-21T10:00:00Z', source: 'Stability AI Blog', tag: 'Launch', related_company_slugs: ['stability-ai'], summary: 'Open-source video generation model released by Stability AI.' },
  { title: 'Cursor Raises $60M Series A Led by a16z', url: 'https://techcrunch.com/2023/08/15/cursor-series-a', published_at: '2023-08-15T12:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['cursor'], summary: 'AI code editor Cursor raises Series A at $400M valuation.' },
  { title: 'Pika Raises $55M for AI Video Generation', url: 'https://techcrunch.com/2023/11/28/pika-funding', published_at: '2023-11-28T14:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['pika'], summary: 'AI video startup Pika raises funding from Lightspeed and others.' },
  { title: 'Together AI Raises $102.5M Series A', url: 'https://techcrunch.com/2024/02/15/together-ai-series-a', published_at: '2024-02-15T10:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['together-ai'], summary: 'GPU cloud platform Together AI raises Series A led by Kleiner Perkins.' },
  { title: 'Lambda Labs Secures $320M Series C', url: 'https://techcrunch.com/2024/02/22/lambda-labs-series-c', published_at: '2024-02-22T11:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['lambda-labs'], summary: 'GPU cloud provider Lambda Labs raises Series C at $1.5B valuation.' },
  { title: 'CoreWeave Raises $1.1B at $19B Valuation', url: 'https://techcrunch.com/2024/05/01/coreweave-funding', published_at: '2024-05-01T10:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['coreweave'], summary: 'Specialized GPU cloud CoreWeave becomes one of most valuable AI infrastructure companies.' },
  { title: 'Glean Raises $200M Series D at $2.2B', url: 'https://techcrunch.com/2024/02/27/glean-series-d', published_at: '2024-02-27T12:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['glean'], summary: 'Enterprise search startup Glean raises Series D led by Kleiner Perkins and Lightspeed.' },
  { title: 'Sierra Emerges from Stealth with $110M Funding', url: 'https://techcrunch.com/2024/01/15/sierra-launch', published_at: '2024-01-15T10:00:00Z', source: 'TechCrunch', tag: 'Launch', related_company_slugs: ['sierra'], summary: 'Conversational AI platform Sierra launches from stealth led by former Salesforce execs.' },
  { title: 'Poolside Raises $500M for AI Software Development', url: 'https://techcrunch.com/2024/04/15/poolside-funding', published_at: '2024-04-15T14:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['poolside'], summary: 'AI coding startup Poolside raises massive round from Bain Capital Ventures and others.' },
  { title: 'Magic Raises $320M for AI Software Engineer', url: 'https://techcrunch.com/2024/07/15/magic-funding', published_at: '2024-07-15T10:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['magic'], summary: 'Autonomous coding agent startup Magic raises large round at $1.5B valuation.' },
  { title: 'Codeium Hits Unicorn Status with $65M Series B', url: 'https://techcrunch.com/2024/01/10/codeium-series-b', published_at: '2024-01-10T12:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['codeium'], summary: 'Free AI coding assistant Codeium reaches $500M valuation.' },
  { title: 'Twelve Labs Raises $50M for Video Understanding AI', url: 'https://techcrunch.com/2024/03/15/twelve-labs-funding', published_at: '2024-03-15T10:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['twelve-labs'], summary: 'Video foundation model company Twelve Labs raises Series A extension.' },
  { title: 'Contextual AI Raises $80M for RAG 2.0 Platform', url: 'https://techcrunch.com/2024/02/20/contextual-ai-funding', published_at: '2024-02-20T12:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['contextual-ai'], summary: 'Enterprise RAG platform Contextual AI raises Series A from Greylock and others.' },
  { title: 'AI Chip Startup Groq Raises $300M at $1B+ Valuation', url: 'https://techcrunch.com/2024/03/01/groq-funding', published_at: '2024-03-01T14:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['groq'], summary: 'LPU chip maker Groq raises Series C led by Tiger Global and D1 Capital.' },
  { title: 'Cerebras Systems Files for IPO', url: 'https://techcrunch.com/2024/06/15/cerebras-ipo', published_at: '2024-06-15T10:00:00Z', source: 'TechCrunch', tag: 'Market', related_company_slugs: ['cerebras-systems'], summary: 'AI hardware company Cerebras confidentially files for IPO.' },
  { title: 'Modular Raises $100M for Mojo and MAX Platform', url: 'https://techcrunch.com/2023/06/15/modular-funding', published_at: '2023-06-15T10:00:00Z', source: 'TechCrunch', tag: 'Funding', related_company_slugs: ['modular'], summary: 'AI infrastructure company Modular raises funding for Mojo programming language.' },
];

async function seed() {
  console.log('🌱 Starting GraphOne database seed...');

  // Seed companies
  console.log('📦 Seeding companies...');
  for (const company of companies) {
    const { error } = await supabaseAdminClient
      .from('companies')
      .upsert(company, { onConflict: 'slug' });
    if (error) {
      console.error(`Error seeding company ${company.slug}:`, error.message);
    }
  }
  console.log(`✅ Seeded ${companies.length} companies`);

  // Seed investors
  console.log('💰 Seeding investors...');
  for (const investor of investors) {
    const { error } = await supabaseAdminClient
      .from('investors')
      .upsert(investor, { onConflict: 'slug' });
    if (error) {
      console.error(`Error seeding investor ${investor.slug}:`, error.message);
    }
  }
  console.log(`✅ Seeded ${investors.length} investors`);

  // Get investor IDs for funding rounds
  const { data: investorData } = await supabaseAdminClient
    .from('investors')
    .select('id, slug');

  const investorMap = new Map(investorData?.map(i => [i.slug, i.id]) || []);

  // Get company IDs for funding rounds
  const { data: companyData } = await supabaseAdminClient
    .from('companies')
    .select('id, slug');

  const companyMap = new Map(companyData?.map(c => [c.slug, c.id]) || []);

  // Seed funding rounds
  console.log('💸 Seeding funding rounds...');
  for (const round of fundingRounds) {
    const companyId = companyMap.get(round.company_slug);
    const leadInvestorId = round.lead_investor_slug ? investorMap.get(round.lead_investor_slug) : null;

    if (!companyId) {
      console.warn(`Company not found for slug: ${round.company_slug}`);
      continue;
    }

    const { error } = await supabaseAdminClient
      .from('funding_rounds')
      .upsert({
        company_id: companyId,
        round_type: round.round_type,
        amount: round.amount,
        currency: round.currency,
        date: round.date,
        lead_investor_id: leadInvestorId,
        co_investors: [],
      }, { onConflict: 'company_id,date,round_type' });
    if (error) {
      console.error(`Error seeding funding round for ${round.company_slug}:`, error.message);
    }
  }
  console.log(`✅ Seeded ${fundingRounds.length} funding rounds`);

  // Seed founders
  console.log('👥 Seeding founders...');
  for (const founder of founders) {
    const companyId = companyMap.get(founder.company_slug);
    if (!companyId) {
      console.warn(`Company not found for founder ${founder.slug}: ${founder.company_slug}`);
      continue;
    }

    const { error } = await supabaseAdminClient
      .from('founders')
      .upsert({
        name: founder.name,
        slug: founder.slug,
        title: founder.title,
        company_id: companyId,
        bio: founder.bio,
        twitter: founder.twitter,
        linkedin: founder.linkedin,
        location: founder.location,
      }, { onConflict: 'slug' });
    if (error) {
      console.error(`Error seeding founder ${founder.slug}:`, error.message);
    }
  }
  console.log(`✅ Seeded ${founders.length} founders`);

  // Seed products
  console.log('🚀 Seeding products...');
  for (const product of products) {
    const companyId = companyMap.get(product.company_slug);
    if (!companyId) {
      console.warn(`Company not found for product: ${product.company_slug}`);
      continue;
    }

    const { error } = await supabaseAdminClient
      .from('products')
      .upsert({
        company_id: companyId,
        name: product.name,
        description: product.description,
        category: product.category,
        launch_date: product.launch_date,
        upvotes: product.upvotes,
        website_url: product.website_url,
      }, { onConflict: 'company_id,name' });
    if (error) {
      console.error(`Error seeding product ${product.name}:`, error.message);
    }
  }
  console.log(`✅ Seeded ${products.length} products`);

  // Seed news articles
  console.log('📰 Seeding news articles...');
  for (const article of newsArticles) {
    const relatedCompanyIds = article.related_company_slugs
      .map(slug => companyMap.get(slug))
      .filter(Boolean);

    const { error } = await supabaseAdminClient
      .from('news_articles')
      .upsert({
        title: article.title,
        url: article.url,
        published_at: article.published_at,
        source: article.source,
        tag: article.tag,
        related_company_ids: relatedCompanyIds,
        summary: article.summary,
      }, { onConflict: 'url' });
    if (error) {
      console.error(`Error seeding news article:`, error.message);
    }
  }
  console.log(`✅ Seeded ${newsArticles.length} news articles`);

  // Refresh materialized views
  console.log('🔄 Refreshing materialized views...');
  const { error: refreshError } = await supabaseAdminClient.rpc('refresh_trending_scores');
  if (refreshError) {
    console.warn('Could not refresh materialized views:', refreshError.message);
  }

  console.log('🎉 Seed completed successfully!');
  process.exit(0);
}

seed().catch(err => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});